"""
Charge le catalogue complet SHM Shop (6 catégories, 95 pagnes réels avec photos)
et initialise le compte administrateur si absent.

    python manage.py load_demo
"""
from django.contrib.auth.models import User
from django.core.management.base import BaseCommand

from shop.models import Category, Product

CATEGORIES = [
    {
        'slug': 'veritable-vlisco',
        'name': 'Véritable Vlisco Wax',
        'description': 'Véritable Wax Hollandais Vlisco authentique 100% coton (6 yards). Motifs iconiques, éclat longue durée et prestige garanti.',
        'icon': '👑',
        'order': 1,
    },
    {
        'slug': 'faux-super',
        'name': 'Faux Super Wax',
        'description': 'Pagne Wax style Super Wax de haute qualité (6 yards). Motifs vibrants, belle tenue et finitions élégantes.',
        'icon': '💎',
        'order': 2,
    },
    {
        'slug': 'faux-vlisco',
        'name': 'Faux Vlisco Wax',
        'description': 'Pagne Wax style Hollandais / Faux Vlisco de très belle qualité (6 yards). Motifs élégants inspirés des grands classiques.',
        'icon': '✨',
        'order': 3,
    },
    {
        'slug': 'super-chiganvy',
        'name': 'Super Chiganvy Wax',
        'description': 'Pagne Wax Super Chiganvy de qualité supérieure (100% coton, 6 yards). Doux, résistant et élégant.',
        'icon': '🧵',
        'order': 4,
    },
    {
        'slug': 'abc-wax',
        'name': 'Véritable ABC Wax',
        'description': 'Collection Véritable ABC Wax 100% coton (6 yards). Motifs vibrants, qualité garantie, parfait pour toutes les tenues.',
        'icon': '🌸',
        'order': 5,
    },
    {
        'slug': 'pagne-simple',
        'name': 'Pagne simple',
        'description': 'Pagne simple 100% coton (6 yards). Motifs variés et colorés, tissu léger et très accessible pour le quotidien.',
        'icon': '🌿',
        'order': 6,
    },
]

PAGNES = [
    # =========================================================================
    # 1. VÉRITABLE VLISCO WAX (12 pagnes à 50 000 FCFA)
    # =========================================================================
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-01', 'name': "Véritable Vlisco Bleu Floral",
        'price': 50000, 'old_price': 55000,
        'motif': "Bleu roi, crème et noir / motifs floraux hollandais",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Tissu d'exception, éclat et tenue incomparables pour les grandes cérémonies.",
        'image': 'products/IMG-20260904-WA0037.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-02', 'name': "Véritable Vlisco Noir & Or Prestige",
        'price': 50000, 'old_price': None,
        'motif': "Noir profond, or et ocre / graphismes géométriques royaux",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Texture noble et couleurs durables au fil des lavages.",
        'image': 'products/IMG-20260904-WA0038.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-03', 'name': "Véritable Vlisco Émeraude Solaire",
        'price': 50000, 'old_price': 54000,
        'motif': "Vert émeraude, jaune safran et marron / rosaces solaires",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Imprimé hollandais authentique d'une finesse incomparable.",
        'image': 'products/IMG-20260904-WA0039.jpg',
        'is_new': True, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-04', 'name': "Véritable Vlisco Rubis & Indigo",
        'price': 50000, 'old_price': None,
        'motif': "Rouge rubis, bleu indigo et touches dorées",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Des motifs classiques très prisés des connaisseurs.",
        'image': 'products/IMG-20260904-WA0040.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-05', 'name': "Véritable Vlisco Céleste & Bronze",
        'price': 50000, 'old_price': 55000,
        'motif': "Bleu ciel, bronze et noir / arabesques traditionnelles",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Élégance pure et douceur du toucher coton haut de gamme.",
        'image': 'products/IMG-20260904-WA0041.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-06', 'name': "Véritable Vlisco Mandarine & Saphir",
        'price': 50000, 'old_price': None,
        'motif': "Orange mandarine, bleu saphir et filigranes noirs",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Nuances vibrantes et rendu spectaculaire en robe ou ensemble.",
        'image': 'products/IMG-20260904-WA0042.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-07', 'name': "Véritable Vlisco Jade & Citron",
        'price': 50000, 'old_price': None,
        'motif': "Vert jade, citron vert et spirales d'ébène",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Fraîcheur et raffinement d'une impression authentique.",
        'image': 'products/IMG-20260904-WA0043.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-08', 'name': "Véritable Vlisco Pourpre Impérial",
        'price': 50000, 'old_price': 56000,
        'motif': "Violet pourpre, lilas et or / médaillons de prestige",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Pourpre intense rehaussé de reflets chauds pour vos grands événements.",
        'image': 'products/IMG-20260904-WA0044.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-09', 'name': "Véritable Vlisco Corail & Noir",
        'price': 50000, 'old_price': None,
        'motif': "Corail doux, noir intense et motifs perlés",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Une pièce maîtresse de la collection hollandaise.",
        'image': 'products/IMG-20260904-WA0045.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-10', 'name': "Véritable Vlisco Turquoise Royal",
        'price': 50000, 'old_price': None,
        'motif': "Bleu turquoise, chocolat et étoiles dorées",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Couleurs éclatantes et motifs géométriques parfaits.",
        'image': 'products/IMG-20260904-WA0046.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-11', 'name': "Véritable Vlisco Soleil Levant",
        'price': 50000, 'old_price': 53000,
        'motif': "Jaune d'or, ocre chaud et volutes fines",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Un rendu lumineux et éclatant pour dames élégantes.",
        'image': 'products/IMG-20260904-WA0047.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'veritable-vlisco',
        'reference': 'SHM-VLISCO-12', 'name': "Véritable Vlisco Nuit Étoilée",
        'price': 50000, 'old_price': None,
        'motif': "Bleu marine sombre, argent et constellation dorée",
        'description': "Véritable Wax Hollandais Vlisco 100% coton (6 yards). Le summum du chic et de la distinction.",
        'image': 'products/IMG-20260904-WA0048.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },

    # =========================================================================
    # 2. FAUX SUPER WAX (9 pagnes à 15 000 FCFA)
    # =========================================================================
    {
        'category_slug': 'faux-super',
        'reference': 'SHM-FSUP-01', 'name': "Faux Super Wax Éclat Doré",
        'price': 15000, 'old_price': 17500,
        'motif': "Jaune moutarde, noir et motifs géométriques Super Wax",
        'description': "Pagne Wax style Super Wax de haute qualité (6 yards). Tissu résistant aux couleurs éclatantes et durables.",
        'image': 'products/IMG-20260904-WA0014.jpg',
        'is_new': True, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'faux-super',
        'reference': 'SHM-FSUP-02', 'name': "Faux Super Wax Bleu Majesté",
        'price': 15000, 'old_price': None,
        'motif': "Bleu roi, crème et arabesques raffinées",
        'description': "Pagne Wax style Super Wax (6 yards). Belle texture et tombé impeccable pour tenues de cérémonie.",
        'image': 'products/IMG-20260904-WA0015.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-super',
        'reference': 'SHM-FSUP-03', 'name': "Faux Super Wax Vert Forêt",
        'price': 15000, 'old_price': 17000,
        'motif': "Vert forêt profond, jaune paille et feuillages",
        'description': "Pagne Wax style Super Wax (6 yards). Harmonie naturelle et motif classique très demandé.",
        'image': 'products/IMG-20260904-WA0016.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-super',
        'reference': 'SHM-FSUP-04', 'name': "Faux Super Wax Cacao & Brique",
        'price': 15000, 'old_price': None,
        'motif': "Marron chocolat, terre cuite et rosaces",
        'description': "Pagne Wax style Super Wax (6 yards). Des teintes chaudes idéales pour confectionner tailleurs et boubous.",
        'image': 'products/IMG-20260904-WA0017.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-super',
        'reference': 'SHM-FSUP-05', 'name': "Faux Super Wax Indigo & Soleil",
        'price': 15000, 'old_price': 18000,
        'motif': "Bleu nuit, jaune lumineux et motifs géométriques",
        'description': "Pagne Wax style Super Wax (6 yards). Contraste éclatant et motif moderne.",
        'image': 'products/IMG-20260904-WA0018.jpg',
        'is_new': True, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'faux-super',
        'reference': 'SHM-FSUP-06', 'name': "Faux Super Wax Prune & Pêche",
        'price': 15000, 'old_price': None,
        'motif': "Prune intense, pêche douce et arabesques",
        'description': "Pagne Wax style Super Wax (6 yards). Couleurs douces et féminines de grande élégance.",
        'image': 'products/IMG-20260904-WA0019.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-super',
        'reference': 'SHM-FSUP-07', 'name': "Faux Super Wax Rubis Cérémonie",
        'price': 15000, 'old_price': None,
        'motif': "Rouge carmin, noir et reflets dorés",
        'description': "Pagne Wax style Super Wax (6 yards). Très festif et élégant pour mariages et fêtes de famille.",
        'image': 'products/IMG-20260904-WA0020.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-super',
        'reference': 'SHM-FSUP-08', 'name': "Faux Super Wax Ambre & Noir",
        'price': 15000, 'old_price': 16500,
        'motif': "Ambre doré, noir et lignes graphiques",
        'description': "Pagne Wax style Super Wax (6 yards). Graphisme soigné et finitions de grande qualité.",
        'image': 'products/IMG-20260904-WA0021.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-super',
        'reference': 'SHM-FSUP-09', 'name': "Faux Super Wax Turquoise Lagon",
        'price': 15000, 'old_price': None,
        'motif': "Bleu turquoise, vert d'eau et spirales",
        'description': "Pagne Wax style Super Wax (6 yards). Fraîcheur et originalité pour toutes vos créations.",
        'image': 'products/IMG-20260904-WA0022.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },

    # =========================================================================
    # 3. FAUX VLISCO WAX (22 pagnes à 15 000 FCFA)
    # =========================================================================
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-01', 'name': "Faux Vlisco 14-5985",
        'price': 15000, 'old_price': 17500,
        'motif': "Jaune soleil et noir / calices floraux et filigranes",
        'description': "Pagne Wax style Hollandais / Faux Vlisco de très belle qualité (6 yards). Motif floral très élégant.",
        'image': 'products/IMG-20260903-WA0018.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-02', 'name': "Faux Vlisco 14-0460",
        'price': 15000, 'old_price': None,
        'motif': "Jaune safran et noir / alphabet et ardoise scolaire",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Motif iconique tableau scolaire, très recherché.",
        'image': 'products/IMG-20260903-WA0019.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-03', 'name': "Faux Vlisco 14-0463",
        'price': 15000, 'old_price': None,
        'motif': "Ocre doré, cacao et noir / médaillons baroques",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Élégance aux tons chauds dorés et cacao.",
        'image': 'products/IMG-20260903-WA0020.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-04', 'name': "Faux Vlisco 14-5983",
        'price': 15000, 'old_price': 17000,
        'motif': "Bleu roi et jaune moutarde / étoiles et constellations",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Bleu royal et nuances dorées intenses pour cérémonies.",
        'image': 'products/IMG-20260903-WA0021.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-05', 'name': "Faux Vlisco 14-0131",
        'price': 15000, 'old_price': None,
        'motif': "Vert pomme et noir / cheval cabré et fers à cheval",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Motif cheval mythique et dynamique sur vert vibrant.",
        'image': 'products/IMG-20260903-WA0022.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-06', 'name': "Faux Vlisco 14-0466",
        'price': 15000, 'old_price': 18000,
        'motif': "Violet cyclamen et noir / médaillons baroques",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Harmonie précieuse de violet intense et noir.",
        'image': 'products/IMG-20260903-WA0023.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-07', 'name': "Faux Vlisco 14-6019",
        'price': 15000, 'old_price': None,
        'motif': "Vert émeraude, jaune et blanc / feuillage tropical",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Végétation luxuriante émeraude et fraîcheur tropicale.",
        'image': 'products/IMG-20260903-WA0024.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-08', 'name': "Faux Vlisco 14-5991",
        'price': 15000, 'old_price': None,
        'motif': "Jaune paille, vert foncé et bordeaux / motif poissons",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Motif poisson symbole de prospérité.",
        'image': 'products/IMG-20260903-WA0025.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-09', 'name': "Faux Vlisco 14-0462",
        'price': 15000, 'old_price': None,
        'motif': "Rouge coquelicot, bleu marine et noir / feuilles d'acanthe",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Motif traditionnel très prisé.",
        'image': 'products/IMG-20260903-WA0026.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-10', 'name': "Faux Vlisco 14-5984",
        'price': 15000, 'old_price': None,
        'motif': "Noir, gris perle et blanc / écailles et résille fine",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Texture visuelle riche et contraste subtil.",
        'image': 'products/IMG-20260903-WA0027.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-11', 'name': "Faux Vlisco 14-0464",
        'price': 15000, 'old_price': None,
        'motif': "Bleu cobalt, jaune moutarde et blanc / paons royaux",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Majesté des paons sur fond bleu cobalt intense.",
        'image': 'products/IMG-20260903-WA0028.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-12', 'name': "Faux Vlisco 14-0465",
        'price': 15000, 'old_price': None,
        'motif': "Kaki olive et rosaces solaires blanches",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Rosaces géométriques parfaites pour robes et ensembles.",
        'image': 'products/IMG-20260903-WA0030.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-13', 'name': "Faux Vlisco 14-5982",
        'price': 15000, 'old_price': None,
        'motif': "Brun havane et noir / damier et étoiles",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Quadrillage damier et étoiles raffinées.",
        'image': 'products/IMG-20260903-WA0031.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-14', 'name': "Faux Vlisco 14-5992",
        'price': 15000, 'old_price': None,
        'motif': "Beige doré, noir et bordeaux / sabliers et entrelacs",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Motif temps et prospérité ultra élégant.",
        'image': 'products/IMG-20260903-WA0033.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-15', 'name': "Faux Vlisco 14-6014",
        'price': 15000, 'old_price': None,
        'motif': "Jaune vif, vert sapin et rouge / plumes stylisées",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Couleurs de fête chaleureuses et éclatantes.",
        'image': 'products/IMG-20260903-WA0037.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-16', 'name': "Faux Vlisco 14-6016",
        'price': 15000, 'old_price': None,
        'motif': "Marron chocolat, turquoise et blanc / losanges ikat",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Graphisme affirmé aux teintes chaudes.",
        'image': 'products/IMG-20260903-WA0039.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-17', 'name': "Faux Vlisco 14-0467",
        'price': 15000, 'old_price': None,
        'motif': "Mauve poudré, or et noir / médaillons baroques",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Un mauve rare rehaussé de touches dorées.",
        'image': 'products/IMG-20260903-WA0029.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-18', 'name': "Faux Vlisco 14-0468",
        'price': 15000, 'old_price': None,
        'motif': "Bleu pétrole, orange brûlé et blanc / roues solaires",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Géométrie moderne et rayonnement lumineux.",
        'image': 'products/IMG-20260903-WA0032.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-19', 'name': "Faux Vlisco 14-0469",
        'price': 15000, 'old_price': None,
        'motif': "Bleu roi, corail et blanc / marguerites graphiques",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Ravissantes fleurs éclatantes sur rayures cobalt.",
        'image': 'products/IMG-20260903-WA0034.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-20', 'name': "Faux Vlisco 14-0470",
        'price': 15000, 'old_price': None,
        'motif': "Vert mousse, ocre et noir / branchages et fleurs",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Feuilles et fleurs d'une belle délicatesse.",
        'image': 'products/IMG-20260903-WA0035.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-21', 'name': "Faux Vlisco 14-0471",
        'price': 15000, 'old_price': None,
        'motif': "Brun cuivré, turquoise et crème / oiseaux chanteurs",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Oiseaux chanteurs dans des branches fleuries.",
        'image': 'products/IMG-20260903-WA0036.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'faux-vlisco',
        'reference': 'SHM-FAUX-22', 'name': "Faux Vlisco 14-0472",
        'price': 15000, 'old_price': 17500,
        'motif': "Jaune canari, rouge bordeaux et noir / motif prestige 500pcs",
        'description': "Pagne Wax style Hollandais / Faux Vlisco (6 yards). Motif collection aux couleurs chaleureuses.",
        'image': 'products/IMG-20260903-WA0038.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },

    # =========================================================================
    # 4. SUPER CHIGANVY WAX (10 pagnes à 9 000 - 10 000 FCFA)
    # =========================================================================
    {
        'category_slug': 'super-chiganvy',
        'reference': 'SHM-CHIG-01', 'name': 'Feuillage Tropical Chiganvy',
        'price': 10000, 'old_price': 12000,
        'motif': 'Vert émeraude et jaune safran / motifs de feuilles',
        'description': 'Pagne Wax Super Chiganvy 100% coton (6 yards). Couleurs éclatantes, parfait pour cérémonies et sorties.',
        'image': 'products/chiganvy-01.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'super-chiganvy',
        'reference': 'SHM-CHIG-02', 'name': 'Rosaces Royales Bleues',
        'price': 10000, 'old_price': None,
        'motif': 'Bleu nuit et or / rosaces et géométrie',
        'description': 'Pagne Wax Super Chiganvy 100% coton (6 yards). Un design royal très recherché pour les mariages.',
        'image': 'products/chiganvy-02.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'super-chiganvy',
        'reference': 'SHM-CHIG-03', 'name': 'Rayures Festives Multicolores',
        'price': 9000, 'old_price': 11000,
        'motif': 'Orange, rouge, vert et noir / lignes dynamiques',
        'description': 'Pagne Wax Super Chiganvy 100% coton (6 yards). Plein de vie et de peps, idéal en tenue moderne.',
        'image': 'products/chiganvy-03.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'super-chiganvy',
        'reference': 'SHM-CHIG-04', 'name': 'Élégance Bordeaux & Crème',
        'price': 10000, 'old_price': None,
        'motif': 'Bordeaux profond et crème / arabesques fines',
        'description': 'Pagne Wax Super Chiganvy 100% coton (6 yards). Une harmonie sobre et raffinée pour dames distinguées.',
        'image': 'products/chiganvy-04.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'super-chiganvy',
        'reference': 'SHM-CHIG-05', 'name': 'Soleil Levant Jaune & Marron',
        'price': 9000, 'old_price': None,
        'motif': 'Jaune moutarde et marron chocolat / volutes solaires',
        'description': 'Pagne Wax Super Chiganvy 100% coton (6 yards). Chaleureux et indémodable.',
        'image': 'products/chiganvy-05.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'super-chiganvy',
        'reference': 'SHM-CHIG-06', 'name': 'Lagon Turquoise',
        'price': 10000, 'old_price': 12500,
        'motif': 'Turquoise et noir / motifs d’écailles modernes',
        'description': 'Pagne Wax Super Chiganvy 100% coton (6 yards). Très frais et lumineux, superbe en robe longue.',
        'image': 'products/chiganvy-06.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'super-chiganvy',
        'reference': 'SHM-CHIG-07', 'name': 'Fleurs d’Or & Indigo',
        'price': 10000, 'old_price': None,
        'motif': 'Bleu indigo et fleurs jaunes d’or',
        'description': 'Pagne Wax Super Chiganvy 100% coton (6 yards). Motif floral classique d’une grande finesse.',
        'image': 'products/chiganvy-07.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'super-chiganvy',
        'reference': 'SHM-CHIG-08', 'name': 'Cercles Géométriques',
        'price': 9000, 'old_price': None,
        'motif': 'Tricolore vert, jaune et noir / cercles concentriques',
        'description': 'Pagne Wax Super Chiganvy 100% coton (6 yards). Graphisme moderne inspiré des traditions africaines.',
        'image': 'products/chiganvy-08.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'super-chiganvy',
        'reference': 'SHM-CHIG-09', 'name': 'Douceur Rose & Or',
        'price': 10000, 'old_price': None,
        'motif': 'Rose pâle et or / fleurs royales',
        'description': 'Pagne Wax Super Chiganvy 100% coton (6 yards). Un mélange précieux de rose et d’or pour vos tenues.',
        'image': 'products/IMG-20260822-WA0013.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'super-chiganvy',
        'reference': 'SHM-CHIG-10', 'name': 'Feuilles du Soir',
        'price': 9000, 'old_price': 11500,
        'motif': 'Blanc cassé / feuilles bordeaux',
        'description': 'Pagne Wax Super Chiganvy 100% coton (6 yards). Un contraste raffiné de bordeaux sur fond clair.',
        'image': 'products/IMG-20260822-WA0006.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },

    # =========================================================================
    # 5. VÉRITABLE ABC WAX (25 pagnes à 6 500 FCFA)
    # =========================================================================
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-01', 'name': 'Motif Mandala Émeraude',
        'price': 6500, 'old_price': 8000,
        'motif': 'Vert émeraude et bleu roi / médaillons orientaux',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Motifs mandala fins et harmonieux.',
        'image': 'products/IMG-20260903-WA0045.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-02', 'name': 'Cacao & Feuilles d’Automne',
        'price': 6500, 'old_price': None,
        'motif': 'Marron chocolat et beige / grandes feuilles stylisées',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Des tons sobres et chauds pour le quotidien.',
        'image': 'products/IMG-20260903-WA0046.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-03', 'name': 'Rosaces Royales Bleues',
        'price': 6500, 'old_price': None,
        'motif': 'Bleu roi intense et beige / spirales et rosaces',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Un bleu éclatant qui met en valeur toutes les silhouettes.',
        'image': 'products/IMG-20260903-WA0047.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-04', 'name': 'Rosaces Royales Vertes',
        'price': 6500, 'old_price': None,
        'motif': 'Vert sapin et ocre beige / rosaces géométriques',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Des rosaces raffinées parfaites pour tailleurs ou robes.',
        'image': 'products/IMG-20260903-WA0048.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-05', 'name': 'Fleurs Solaires Indigo',
        'price': 6500, 'old_price': 8000,
        'motif': 'Bleu indigo et jaune soleil / fleurs étoilées',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Contraste éclatant bleu et jaune pour les fêtes.',
        'image': 'products/IMG-20260903-WA0049.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-06', 'name': 'Fleurs Étoilées Chocolat',
        'price': 6500, 'old_price': None,
        'motif': 'Brun chocolat et crème / fleurs géométriques',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Un classique indémodable aux teintes naturelles.',
        'image': 'products/IMG-20260903-WA0050.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-07', 'name': 'Tourbillons Noirs & Dorés',
        'price': 6500, 'old_price': None,
        'motif': 'Noir profond et jaune paille / volutes et cercles',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Graphisme moderne très prisé des jeunes créateurs.',
        'image': 'products/IMG-20260903-WA0051.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-08', 'name': 'Éventails Baroques Marron',
        'price': 6500, 'old_price': None,
        'motif': 'Terre de Sienne et noir / éventails et arabesques',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Un motif riche et structuré pour ensembles chics.',
        'image': 'products/IMG-20260903-WA0052.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-09', 'name': 'Éventails Baroques Indigo',
        'price': 6500, 'old_price': None,
        'motif': 'Bleu nuit et noir / éventails baroques',
        'description': 'Véritable ABC Wax 100% coton (6 yards). L’alliance du bleu nuit et du noir pour un look habillé.',
        'image': 'products/IMG-20260903-WA0053.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-10', 'name': 'Plumes Royales Bleues',
        'price': 6500, 'old_price': None,
        'motif': 'Bleu cobalt et blanc / grandes plumes de paon',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Des plumes majestueuses très dynamiques.',
        'image': 'products/IMG-20260903-WA0054.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-11', 'name': 'Mosaïque Émeraude & Or',
        'price': 6500, 'old_price': 8000,
        'motif': 'Vert émeraude et ocre doré / motifs géométriques fins',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Une mosaïque élégante pour vos sorties du dimanche.',
        'image': 'products/IMG-20260903-WA0055.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-12', 'name': 'Ondulations Noires & Blanches',
        'price': 6500, 'old_price': None,
        'motif': 'Noir et blanc / ondes géométriques psychédéliques',
        'description': 'Véritable ABC Wax 100% coton (6 yards). L’élégance intemporelle du noir et blanc.',
        'image': 'products/IMG-20260903-WA0056.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-13', 'name': 'Mosaïque Marine & Marron',
        'price': 6500, 'old_price': None,
        'motif': 'Bleu marine, noisette et noir / damier géométrique',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Harmonie parfaite pour tenues professionnelles et chemises.',
        'image': 'products/IMG-20260903-WA0057.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-14', 'name': 'Palmiers Bleus & Ocre',
        'price': 6500, 'old_price': None,
        'motif': 'Bleu cobalt et ocre / palmes tropicales stylisées',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Une touche d’exotisme et de fraîcheur.',
        'image': 'products/IMG-20260903-WA0058.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-15', 'name': 'Palmiers Verts & Noirs',
        'price': 6500, 'old_price': None,
        'motif': 'Vert forêt et noir / palmes tropicales',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Un motif végétal profond et majestueux.',
        'image': 'products/IMG-20260903-WA0059.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-16', 'name': 'Palmiers Marron & Crème',
        'price': 6500, 'old_price': None,
        'motif': 'Marron chaud et crème / feuillage tropical',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Idéal pour robes longues décontractées.',
        'image': 'products/IMG-20260903-WA0060.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-17', 'name': 'Cercles & Étoiles Émeraude',
        'price': 6500, 'old_price': None,
        'motif': 'Vert émeraude et jaune paille / cercles entrelacés',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Motifs rythmés et dynamiques aux couleurs vives.',
        'image': 'products/IMG-20260903-WA0061.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-18', 'name': 'Cercles & Étoiles Indigo',
        'price': 6500, 'old_price': None,
        'motif': 'Bleu indigo et jaune d’or / cercles concentriques',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Un des motifs les plus appréciés de la gamme ABC Wax.',
        'image': 'products/IMG-20260903-WA0062.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-19', 'name': 'Soleil Levant Ocre & Noir',
        'price': 6500, 'old_price': None,
        'motif': 'Ocre doré et noir / rayons solaires graphiques',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Graphisme puissant rappelant la lumière africaine.',
        'image': 'products/IMG-20260903-WA0063.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-20', 'name': 'Soleil Levant Marine & Noir',
        'price': 6500, 'old_price': None,
        'motif': 'Bleu marine profond et noir / rayons graphiques',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Sobriété et distinction pour toute la famille.',
        'image': 'products/IMG-20260903-WA0064.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-21', 'name': 'Jardin Tropical Bleu & Marron',
        'price': 6500, 'old_price': None,
        'motif': 'Bleu roi, marron chocolat et blanc / feuillage',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Une combinaison de couleurs très prisée.',
        'image': 'products/IMG-20260903-WA0065.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-22', 'name': 'Jardin Tropical Vert & Marron',
        'price': 6500, 'old_price': None,
        'motif': 'Vert menthe, marron glacé et crème / feuillage',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Douceur pastel et élégance discrète.',
        'image': 'products/IMG-20260903-WA0066.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-23', 'name': 'Classique ABC Jaune Solaire',
        'price': 6500, 'old_price': None,
        'motif': 'Jaune d’or, noir et bordeaux / motifs traditionnels',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Tissu doux et résistant pour toutes occasions.',
        'image': 'products/IMG-20260822-WA0007.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-24', 'name': 'Classique ABC Bleu Nuit',
        'price': 6500, 'old_price': 8000,
        'motif': 'Bleu nuit, vert émeraude et blanc / fleurs géométriques',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Un classique apprécié pour les uniformes d’associations.',
        'image': 'products/IMG-20260822-WA0010.jpg',
        'is_new': False, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'abc-wax',
        'reference': 'SHM-ABC-25', 'name': 'Classique ABC Ocre Chic',
        'price': 6500, 'old_price': None,
        'motif': 'Ocre chaud et noir / volutes baroques',
        'description': 'Véritable ABC Wax 100% coton (6 yards). Teintes terreuses nobles et intemporelles.',
        'image': 'products/IMG-20260822-WA0012.jpg',
        'is_new': False, 'is_promo': False, 'is_available': True,
    },

    # =========================================================================
    # 6. PAGNE SIMPLE (17 pagnes à 2 500 FCFA)
    # =========================================================================
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-01', 'name': 'Pagne Simple Ardoise Scolaire',
        'price': 2500, 'old_price': 3000,
        'motif': 'Vert émeraude, bordeaux et chiffres scolaires / ardoises',
        'description': 'Pagne simple 100% coton (6 yards). Motif iconique éducation et chiffres sur fond vert.',
        'image': 'products/IMG-20260904-WA0049.jpg',
        'is_new': True, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-02', 'name': 'Pagne Simple Rosaces Violet & Nuit',
        'price': 2500, 'old_price': None,
        'motif': 'Violet prune, bleu nuit et turquoise / rosaces perlées',
        'description': 'Pagne simple 100% coton (6 yards). Nuances profondes et motif traditionnel très prisé.',
        'image': 'products/IMG-20260904-WA0051.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-03', 'name': 'Pagne Simple Pétales Vert Solaire',
        'price': 2500, 'old_price': None,
        'motif': 'Vert clair, jaune safran et noir / grandes corolles florales',
        'description': 'Pagne simple 100% coton (6 yards). Lumineux et dynamique pour tenues quotidiennes.',
        'image': 'products/IMG-20260904-WA0052.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-04', 'name': 'Pagne Simple Bleu Roi & Fleurs d’Or',
        'price': 2500, 'old_price': 3000,
        'motif': 'Bleu royal, jaune soleil et blanc / rayures et fleurs',
        'description': 'Pagne simple 100% coton (6 yards). Un superbe contraste bleu et jaune très vivant.',
        'image': 'products/IMG-20260904-WA0053.jpg',
        'is_new': True, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-05', 'name': 'Pagne Simple Médaillons Marine & Vert',
        'price': 2500, 'old_price': None,
        'motif': 'Bleu marine, vert anis et blanc / médaillons perlés et bordures',
        'description': 'Pagne simple 100% coton (6 yards). Graphisme soigné avec de belles bordures coordonnées.',
        'image': 'products/IMG-20260904-WA0054.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-06', 'name': 'Pagne Simple Fleurs Étoilées Émeraude',
        'price': 2500, 'old_price': None,
        'motif': 'Vert émeraude, noir et blanc cassé / fleurs stellaires et feuillages',
        'description': 'Pagne simple 100% coton (6 yards). Motif végétal raffiné pour robes et pagnes noués.',
        'image': 'products/IMG-20260904-WA0055.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-07', 'name': 'Pagne Simple Fleurs 4 Pétales Azur',
        'price': 2500, 'old_price': None,
        'motif': 'Bleu cobalt, jaune citron et noir / fleurs 4 pétales',
        'description': 'Pagne simple 100% coton (6 yards). Des motifs graphiques vibrants et joyeux.',
        'image': 'products/IMG-20260904-WA0056.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-08', 'name': 'Pagne Simple Étoiles Jaune & Indigo',
        'price': 2500, 'old_price': 3000,
        'motif': 'Jaune moutarde, bleu indigo et noir / rosaces en chaîne',
        'description': 'Pagne simple 100% coton (6 yards). Motifs en maillons géométriques très élégants.',
        'image': 'products/IMG-20260904-WA0057.jpg',
        'is_new': True, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-09', 'name': 'Pagne Simple Glory Vert & Mosaïque',
        'price': 2500, 'old_price': None,
        'motif': 'Vert végétal, crème et noir / feuilles d’acanthe sur mosaïque fine',
        'description': 'Pagne simple 100% coton (6 yards). Réf 2620210. Imprimé net et finitions soignées.',
        'image': 'products/IMG-20260904-WA0050.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-10', 'name': 'Pagne Simple Glory Orange & Feuillages',
        'price': 2500, 'old_price': None,
        'motif': 'Orange mandarine, cacao et crème / grandes feuilles tropicales',
        'description': 'Pagne simple 100% coton (6 yards). Réf 2620205. Teintes chaudes et éclatantes.',
        'image': 'products/IMG-20260904-WA0058.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-11', 'name': 'Pagne Simple Glory Paon Royal Bleu',
        'price': 2500, 'old_price': 3000,
        'motif': 'Bleu outremer, marron chocolat et or / plumes de paon',
        'description': 'Pagne simple 100% coton (6 yards). Réf 2620209. Motif majestueux très recherché.',
        'image': 'products/IMG-20260904-WA0059.jpg',
        'is_new': True, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-12', 'name': 'Pagne Simple Glory Coquillages & Ébène',
        'price': 2500, 'old_price': None,
        'motif': 'Noir perlé, ocre et bordeaux / coquillages royaux',
        'description': 'Pagne simple 100% coton (6 yards). Réf 2620207. Design raffiné sur fond noir constellé.',
        'image': 'products/IMG-20260904-WA0060.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-13', 'name': 'Pagne Simple Glory Rosaces Royales Indigo',
        'price': 2500, 'old_price': None,
        'motif': 'Bleu indigo, or et crème / rosaces solaires',
        'description': 'Pagne simple 100% coton (6 yards). Réf 2620204. Des rosaces lumineuses très élégantes.',
        'image': 'products/IMG-20260904-WA0061.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-14', 'name': 'Pagne Simple Glory Lagon & Chevrons',
        'price': 2500, 'old_price': 3000,
        'motif': 'Turquoise lagon, vert olive et noir / chevrons graphiques',
        'description': 'Pagne simple 100% coton (6 yards). Réf 2620203. Motifs géométriques ultra modernes.',
        'image': 'products/IMG-20260904-WA0062.jpg',
        'is_new': True, 'is_promo': True, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-15', 'name': 'Pagne Simple Glory Carrés Célestes & Vert',
        'price': 2500, 'old_price': None,
        'motif': 'Vert vif, bleu ciel et noir / carrés concentriques modernes',
        'description': 'Pagne simple 100% coton (6 yards). Réf 2620201. Graphisme contemporain très tendance.',
        'image': 'products/IMG-20260904-WA0063.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-16', 'name': 'Pagne Simple Glory Carrés Pourpre & Orange',
        'price': 2500, 'old_price': None,
        'motif': 'Pourpre magenta, orange vif et noir / carrés concentriques',
        'description': 'Pagne simple 100% coton (6 yards). Réf 2620202. Couleurs éclatantes et vibrantes.',
        'image': 'products/IMG-20260904-WA0064.jpg',
        'is_new': True, 'is_promo': False, 'is_available': True,
    },
    {
        'category_slug': 'pagne-simple',
        'reference': 'SHM-SMPL-17', 'name': 'Pagne Simple Glory Papillon Doré',
        'price': 2500, 'old_price': 3000,
        'motif': 'Ocre doré, bordeaux et noir / grand papillon stylisé',
        'description': 'Pagne simple 100% coton (6 yards). Réf 2620206. Motif papillon majestueux et symbolique.',
        'image': 'products/IMG-20260904-WA0065.jpg',
        'is_new': True, 'is_promo': True, 'is_available': True,
    },
]


class Command(BaseCommand):
    help = 'Charge les catégories et le catalogue complet SHM Shop (95 pagnes).'

    def handle(self, *args, **options):
        # 1. Catégories
        cats = {}
        for cdata in CATEGORIES:
            cat, _ = Category.objects.update_or_create(
                slug=cdata['slug'],
                defaults=cdata,
            )
            cats[cdata['slug']] = cat
        self.stdout.write(self.style.SUCCESS(f'{len(cats)} catégorie(s) configurée(s).'))

        # Nettoyage des anciennes catégories orphelines si nécessaire
        Category.objects.exclude(slug__in=[c['slug'] for c in CATEGORIES]).delete()

        # 2. Produits
        created = 0
        current_refs = []
        for pdata in PAGNES:
            data = dict(pdata)
            cat_slug = data.pop('category_slug')
            data['category'] = cats.get(cat_slug)
            current_refs.append(data['reference'])

            prod, was_created = Product.objects.update_or_create(
                reference=data['reference'],
                defaults=data,
            )
            created += int(was_created)

        # Supprimer les anciens produits non présents
        Product.objects.exclude(reference__in=current_refs).delete()

        total = Product.objects.count()
        self.stdout.write(self.style.SUCCESS(
            f'{created} pagne(s) créé(s) / {total} pagne(s) au total dans le catalogue.'
        ))

        # 3. Compte administrateur démo si absent
        admin_user = 'shmadmin'
        admin_pass = 'shmshop2026'
        admin_email = 'contact@shmshop.bj'
        if not User.objects.filter(username=admin_user).exists():
            User.objects.create_superuser(
                username=admin_user,
                email=admin_email,
                password=admin_pass
            )
            self.stdout.write(self.style.SUCCESS(
                f'Compte administrateur créé : {admin_user} / {admin_pass}'
            ))
        else:
            self.stdout.write(self.style.NOTICE(
                f'Compte administrateur démo ({admin_user}) déjà présent.'
            ))
