# Generated by Django 6.1.1 on 2026-09-02 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('reference', models.CharField(help_text='Ex. SHM-001', max_length=20, unique=True, verbose_name='Référence')),
                ('price', models.PositiveIntegerField(verbose_name='Prix (FCFA)')),
                ('old_price', models.PositiveIntegerField(blank=True, help_text='Renseigner uniquement en cas de promotion.', null=True, verbose_name='Ancien prix (FCFA)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('motif', models.CharField(blank=True, max_length=120, verbose_name='Motif / couleurs')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Photo principale')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_new', models.BooleanField(default=False, verbose_name='Nouveauté')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
            ],
            options={
                'verbose_name': 'Pagne',
                'verbose_name_plural': 'Pagnes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Photo')),
                ('alt', models.CharField(blank=True, max_length=120, verbose_name='Description de la photo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'Photo supplémentaire',
                'verbose_name_plural': 'Photos supplémentaires',
            },
        ),
    ]
