# Generated by Django 6.1.1 on 2026-09-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='✨', help_text='Ex. ✨, 👑, 🌿, 💎', max_length=20, verbose_name='Icône ou Emoji')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='En stock (disponible)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_promo',
            field=models.BooleanField(default=False, verbose_name='En promotion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='motif',
            field=models.CharField(blank=True, max_length=140, verbose_name='Motif et couleurs'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom du pagne'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(help_text='Ex. ABC-001, ORI-001, CHIG-001', max_length=30, unique=True, verbose_name='Référence'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Catégorie'),
        ),
    ]
